Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -46,13 +46,29 @@ jobs:
           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           GITHUB_TOKEN: ${{ github.token }}
-          
       - name: Manifest Generation
         run: |
-          docker image ls
-          curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | shasum -a 256 ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          sh install.sh
+          rm install.sh install.sh.checksum
           billy generate \
               --access-token "${{ secrets.GITHUB_TOKEN }}" \
-             --aqua-key "${{ secrets.AQUA_KEY }}" \
-             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-             --artifact-path "saargondocker/graphql-vuln:${{ github.sha }}"
+              --aqua-key "${{ secrets.AQUA_KEY }}" \
+              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+
+              # The docker image name:tag of the newly built image
+              --artifact-path "saargondocker/graphql-vuln:${{ github.sha }}" \
+     # - name: Manifest Generation
+     #   run: |
+     #     docker image ls
+     #     curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
+     #     billy generate \
+     #         --access-token "${{ secrets.GITHUB_TOKEN }}" \
+     #        --aqua-key "${{ secrets.AQUA_KEY }}" \
+     #        --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+     #        --artifact-path "saargondocker/graphql-vuln:${{ github.sha }}"
